# Generated by Django 3.1.7 on 2021-03-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='identifier',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='reference',
        ),
    ]
