# Generated by Django 3.1.7 on 2021-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210328_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='identifier',
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='uid',
            field=models.CharField(default='urn:oid:1.2.3.4.5', max_length=100, verbose_name='UID'),
        ),
        migrations.AddField(
            model_name='instance',
            name='uid',
            field=models.CharField(default='urn:oid:1.2.3.4.5', max_length=100, verbose_name='UID'),
        ),
        migrations.AddField(
            model_name='series',
            name='uid',
            field=models.CharField(default='urn:oid:1.2.3.4.5', max_length=100, verbose_name='UID'),
        ),
    ]
