# Generated by Django 3.1.7 on 2021-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210329_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingstudy',
            name='identifier',
            field=models.CharField(max_length=100, null=True, verbose_name='Идентификатор'),
        ),
    ]
