# Generated by Django 3.1.7 on 2021-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210329_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='dicom_file',
            field=models.FileField(null=True, upload_to='dicoms/', verbose_name='DICOM Файл'),
        ),
    ]
