# Generated by Django 3.1.7 on 2021-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_series_dicom_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image_field',
            field=models.ImageField(null=True, upload_to='2', verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='series',
            name='reference',
            field=models.URLField(max_length=1000, null=True, verbose_name='Ссылка'),
        ),
    ]
