# Generated by Django 3.1.7 on 2021-03-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210330_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='series',
            name='dicom_file',
            field=models.FileField(blank=True, null=True, upload_to='dicoms/', verbose_name='DICOM Файл'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='2', verbose_name='1'),
        ),
    ]
