# Generated by Django 3.1.7 on 2021-03-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210330_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='series/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='series',
            name='reference',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
    ]
