# Generated by Django 3.1.7 on 2021-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_analized',
            field=models.BooleanField(default=False, verbose_name='Проанализирован'),
        ),
        migrations.AddField(
            model_name='instance',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Вероятность'),
        ),
    ]
